heat_template_version: 2014-10-16  
description: A simple auto scaling group with LBaaS V2 Service.
parameters:
  my_flavor:
    type: string
    description: Flavor for the server to be created
    default: "m1.small"
    constraints:
      - custom_constraint: nova.flavor
  my_accesskey:
    type: string
    description: Name of an existing key-pair
    default: "naim_key"
    constraints:
      - custom_constraint: nova.keypair
  my_image:
    type: string
    description: Image ID or image name to use for the server
    default: "Cirros"
    constraints:
      - custom_constraint: glance.image
  my_network:
    type: string
    description: Neutron Network
    default: "NAIM-WEB"
    constraints:
      - custom_constraint: neutron.network
  my_subnet:
    type: string
    description: Neutron SUB-Network
    default: "NAIM_WEB"
  my_zone:
    type: string
    description: Availability Zone
    default: "nova"
  app_port:
    type: string
    description: Aplication TCP Port
    default: "80"

resources:
  group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 1
      max_size: 5
      min_size: 1
      resource:
        type: http://192.168.91.109:8000/srv_template.yaml
        properties:
          metadata: {"metering.stack": {get_param: "OS::stack_id"}}
          pool_id: { get_resource: pool }
          flavor: { get_param: my_flavor }
          network: { get_param: my_network }
          key_name: {get_param: my_accesskey }
          subnet: { get_param: my_subnet }
          image: { get_param: my_image }
          app_port: { get_param: app_port }
  monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      delay: 5
      type: HTTP
      timeout: 5
      max_retries: 3
      pool: { get_resource: pool }
  pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      listener: { get_resource: listener }
  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: lb }
      protocol: HTTP
      protocol_port: { get_param: app_port }
  lb:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: { get_param: my_subnet }
  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group }
      cooldown: 60
      scaling_adjustment: 1
  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group }
      cooldown: 60
      scaling_adjustment: -1
  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      description: Scale-up if the average CPU > 50% for 1 minute
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 50
      alarm_actions:
        - {get_attr: [scaleup_policy, alarm_url]}
      comparison_operator: gt
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
  cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      description: Scale-down if the average CPU < 15% for 10 minutes
      statistic: avg
      period: 600
      evaluation_periods: 1
      threshold: 15
      alarm_actions:
        - {get_attr: [scaledown_policy, alarm_url]}
      comparison_operator: lt
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}

outputs:
  Scale-UP-URL:
    value: {get_attr: [scaleup_policy, alarm_url]}
    description: Scale-UP ALARM URL
  Scale-DOWN-URL:
    value: {get_attr: [scaledown_policy, alarm_url]}
    description: Scale-DOWN ALARM URL
  Scale-UP-SIGNAL-URL:
    value: {get_attr: [scaleup_policy, signal_url]}
    description: Scale-UP Signal URL
  Scale-DOWN-SIGNAL-URL:
    value: {get_attr: [scaledown_policy, signal_url]}
    description: Scale-DOWN Signal URL
  LB-URL-VIP:
    value: {get_attr: [lb, vip_address]}
    description: VIP for our Load Balancer
