heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for servers
    default: WebSrvTemplate
  key_name:
    type: string
    description: SSH key to connect to the servers
    default: key
  flavor:
    type: string
    description: flavor used by the servers
    default: s1.large
  network:
    type: string
    description: Network used by the server
    default: Internal_Network
 
resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      networks: [{network: {get_param: network} }]
 
outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
